In [ ]:
import pandas as pd
import numpy as np
import os

In [ ]:
from google.colab import drive

drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
folder_path = '/content/drive/MyDrive/Ecommerce Business and Customer Analytics/Data/raw'

In [ ]:
os.listdir(folder_path)

['orders.xlsx',
 'customers.xlsx',
 'order_items.xlsx',
 'events.xlsx',
 'products.xlsx',
 'sessions.xlsx',
 'reviews.xlsx']

In [ ]:
customers = pd.read_excel(f'{folder_path}/customers.xlsx')
products = pd.read_excel(f'{folder_path}/products.xlsx')
sessions = pd.read_excel(f'{folder_path}/sessions.xlsx')
events = pd.read_excel(f'{folder_path}/events.xlsx')
orders = pd.read_excel(f'{folder_path}/orders.xlsx')
order_items = pd.read_excel(f'{folder_path}/order_items.xlsx')
reviews = pd.read_excel(f'{folder_path}/reviews.xlsx')

In [ ]:
tables = {
    'customers': customers,
    'products': products,
    'sessions': sessions,
    'events': events,
    'orders': orders,
    'order_items': order_items,
    'reviews': reviews
}

In [ ]:
for name, df in tables.items():
    print(f'{name}: {df.shape}')

customers: (20000, 7)
products: (1197, 6)
sessions: (120000, 6)
events: (760958, 10)
orders: (33580, 10)
order_items: (59163, 5)
reviews: (10780, 6)

In [ ]:
for name, df in tables.items():
    print(f'\n{name}:')
    print(list(df.columns))

customers:
['customer_id', 'name', 'email', 'country', 'age', 'signup_date', 'marketing_opt_in']

products:
['product_id', 'category', 'name', 'price_usd', 'cost_usd', 'margin_usd']

sessions:
['session_id', 'customer_id', 'start_time', 'device', 'source', 'country']

events:
['event_id', 'session_id', 'timestamp', 'event_type', 'product_id', 'qty', 'cart_size', 'payment', 'discount_pct', 'amount_usd']

orders:
['order_id', 'customer_id', 'order_time', 'payment_method', 'discount_pct', 'subtotal_usd', 'total_usd', 'country', 'device', 'source']

order_items:
['order_id', 'product_id', 'unit_price_usd', 'quantity', 'line_total_usd']

reviews:
['review_id', 'order_id', 'product_id', 'rating', 'review_text', 'review_time']

In [ ]:
for name, df in tables.items():
    print()
    print(name.upper())
    print()
    print(df.dtypes)
    print()
    print()

CUSTOMERS

customer_id                  int64
name                        object
email                       object
country                     object
age                          int64
signup_date         datetime64[ns]
marketing_opt_in              bool
dtype: object



PRODUCTS

product_id      int64
category       object
name           object
price_usd     float64
cost_usd      float64
margin_usd    float64
dtype: object



SESSIONS

session_id      int64
customer_id     int64
start_time     object
device         object
source         object
country        object
dtype: object



EVENTS

event_id          int64
session_id        int64
timestamp        object
event_type       object
product_id      float64
qty             float64
cart_size       float64
payment          object
discount_pct     object
amount_usd      float64
dtype: object



ORDERS

order_id            int64
customer_id         int64
order_time         object
payment_method     object
discount_pct        int64
subtotal_usd      float64
total_usd         float64
country            object
device             object
source             object
dtype: object



ORDER_ITEMS

order_id            int64
product_id          int64
unit_price_usd    float64
quantity            int64
line_total_usd    float64
dtype: object



REVIEWS

review_id       int64
order_id        int64
product_id      int64
rating          int64
review_text    object
review_time    object
dtype: object

In [ ]:
missing_summary = []

for name, df in tables.items():
    for column in df.columns:
        missing_summary.append({
            'Table': name,
            'Column': column,
            'Blank Values': df[column].isnull().sum(),
            'Blank %': round(df[column].isnull().mean() * 100, 2)
        })

missing_df = pd.DataFrame(missing_summary)

display(missing_df)

          Table            Column  Blank Values  Blank %
0     customers       customer_id             0     0.00
1     customers              name             0     0.00
2     customers             email             0     0.00
3     customers           country             0     0.00
4     customers               age             0     0.00
5     customers       signup_date             0     0.00
6     customers  marketing_opt_in             0     0.00
7      products        product_id             0     0.00
8      products          category             0     0.00
9      products              name             0     0.00
10     products         price_usd             0     0.00
11     products          cost_usd             0     0.00
12     products        margin_usd             0     0.00
13     sessions        session_id             0     0.00
14     sessions       customer_id             0     0.00
15     sessions        start_time             0     0.00
16     sessions            device             0     0.00
17     sessions            source             0     0.00
18     sessions           country             0     0.00
19       events          event_id             0     0.00
20       events        session_id             0     0.00
21       events         timestamp             0     0.00
22       events        event_type             0     0.00
23       events        product_id         78489    10.31
24       events               qty        617832    81.19
25       events         cart_size        716049    94.10
26       events           payment        727378    95.59
27       events      discount_pct        727377    95.59
28       events        amount_usd        727378    95.59
29       orders          order_id             0     0.00
30       orders       customer_id             0     0.00
31       orders        order_time             0     0.00
32       orders    payment_method             0     0.00
33       orders      discount_pct             0     0.00
34       orders      subtotal_usd             0     0.00
35       orders         total_usd             0     0.00
36       orders           country             0     0.00
37       orders            device             0     0.00
38       orders            source             0     0.00
39  order_items          order_id             0     0.00
40  order_items        product_id             0     0.00
41  order_items    unit_price_usd             0     0.00
42  order_items          quantity             0     0.00
43  order_items    line_total_usd             0     0.00
44      reviews         review_id             0     0.00
45      reviews          order_id             0     0.00
46      reviews        product_id             0     0.00
47      reviews            rating             0     0.00
48      reviews       review_text             0     0.00
49      reviews       review_time             0     0.00

In [ ]:
duplicate_summary = []

for name, df in tables.items():
    duplicate_summary.append({
        'Table': name,
        'Total Rows': len(df),
        'Duplicate Rows': df.duplicated().sum(),
        'Duplicate %': round(df.duplicated().mean() * 100, 2)
    })

duplicate_df = pd.DataFrame(duplicate_summary)

display(duplicate_df)

         Table  Total Rows  Duplicate Rows  Duplicate %
0    customers       20000               0         0.00
1     products        1197               0         0.00
2     sessions      120000               0         0.00
3       events      760958               0         0.00
4       orders       33580               0         0.00
5  order_items       59163              73         0.12
6      reviews       10780               0         0.00

In [ ]:
# CUSTOMERS
customers['signup_date'] = pd.to_datetime(
    customers['signup_date'],
    errors='coerce'
)

# SESSIONS
sessions['start_time'] = pd.to_datetime(
    sessions['start_time'],
    errors='coerce'
)

# EVENTS
events['timestamp'] = pd.to_datetime(
    events['timestamp'],
    errors='coerce'
)

# Nullable integers because these columns contain NaN
events['product_id'] = events['product_id'].astype('Int64')
events['qty'] = events['qty'].astype('Int64')
events['cart_size'] = events['cart_size'].astype('Int64')

# Converting discount from object → numeric
events['discount_pct'] = pd.to_numeric(
    events['discount_pct'],
    errors='coerce'
)

# ORDERS
orders['order_time'] = pd.to_datetime(
    orders['order_time'],
    errors='coerce'
)

# REVIEWS
reviews['review_time'] = pd.to_datetime(
    reviews['review_time'],
    errors='coerce'
)

In [ ]:
for name, df in tables.items():
    print()
    print(name.upper())
    print()
    print(df.dtypes)

CUSTOMERS

customer_id                  int64
name                        object
email                       object
country                     object
age                          int64
signup_date         datetime64[ns]
marketing_opt_in              bool
dtype: object

PRODUCTS

product_id      int64
category       object
name           object
price_usd     float64
cost_usd      float64
margin_usd    float64
dtype: object

SESSIONS

session_id              int64
customer_id             int64
start_time     datetime64[ns]
device                 object
source                 object
country                object
dtype: object

EVENTS

event_id                 int64
session_id               int64
timestamp       datetime64[ns]
event_type              object
product_id               Int64
qty                      Int64
cart_size                Int64
payment                 object
discount_pct           float64
amount_usd             float64
dtype: object

ORDERS

order_id                   int64
customer_id                int64
order_time        datetime64[ns]
payment_method            object
discount_pct               int64
subtotal_usd             float64
total_usd                float64
country                   object
device                    object
source                    object
dtype: object

ORDER_ITEMS

order_id            int64
product_id          int64
unit_price_usd    float64
quantity            int64
line_total_usd    float64
dtype: object

REVIEWS

review_id               int64
order_id                int64
product_id              int64
rating                  int64
review_text            object
review_time    datetime64[ns]
dtype: object

In [ ]:
print("Before deleting duplicate rows:")
print("Rows:", len(order_items))
print("Duplicate rows:", order_items.duplicated().sum())

Before deleting duplicate rows:
Rows: 59163
Duplicate rows: 73

In [ ]:
order_items = order_items.drop_duplicates(keep='first').reset_index(drop=True)

In [ ]:
print("After deleting duplicate rows:")
print("Rows:", len(order_items))
print("Duplicate rows:", order_items.duplicated().sum())

After deleting duplicate rows:
Rows: 59090
Duplicate rows: 0

In [ ]:
tables = {
    'customers': customers,
    'products': products,
    'sessions': sessions,
    'events': events,
    'orders': orders,
    'order_items': order_items,
    'reviews': reviews
}

In [ ]:
print("Customers:")
print("Total rows:", len(customers))
print("Unique customer_id:", customers['customer_id'].nunique())

Customers:
Total rows: 20000
Unique customer_id: 20000

In [ ]:
print("Products:")
print("Total rows:", len(products))
print("Unique product_id:", products['product_id'].nunique())

Products:
Total rows: 1197
Unique product_id: 1197

In [ ]:
print("Sessions:")
print("Total rows:", len(sessions))
print("Unique session_id:", sessions['session_id'].nunique())

Sessions:
Total rows: 120000
Unique session_id: 120000

In [ ]:
print("Events:")
print("Total rows:", len(events))
print("Unique event_id:", events['event_id'].nunique())

Events:
Total rows: 760958
Unique event_id: 760958

In [ ]:
print("Orders:")
print("Total rows:", len(orders))
print("Unique order_id:", orders['order_id'].nunique())

Orders:
Total rows: 33580
Unique order_id: 33580

In [ ]:
print("Reviews:")
print("Total rows:", len(reviews))
print("Unique review_id:", reviews['review_id'].nunique())

Reviews:
Total rows: 10780
Unique review_id: 10780

In [ ]:
print("Order Items:")

composite_duplicates = order_items.duplicated(
    subset=['order_id', 'product_id']
).sum()

print("Total rows:", len(order_items))
print("Duplicate order_id + product_id combinations:", composite_duplicates)

Order Items:
Total rows: 59090
Duplicate order_id + product_id combinations: 37

In [ ]:
# Foreign Key Integrity Check

print("FOREIGN KEY INTEGRITY\n")

# 1. sessions.customer_id → customers.customer_id
invalid_sessions_customer = sessions[
    ~sessions['customer_id'].isin(customers['customer_id'])
]

print("1. sessions.customer_id → customers.customer_id")
print("Invalid rows:", len(invalid_sessions_customer))


# 2. orders.customer_id → customers.customer_id
invalid_orders_customer = orders[
    ~orders['customer_id'].isin(customers['customer_id'])
]

print("\n2. orders.customer_id → customers.customer_id")
print("Invalid rows:", len(invalid_orders_customer))


# 3. events.session_id → sessions.session_id
invalid_events_session = events[
    ~events['session_id'].isin(sessions['session_id'])
]

print("\n3. events.session_id → sessions.session_id")
print("Invalid rows:", len(invalid_events_session))


# 4. events.product_id → products.product_id
invalid_events_product = events[
    events['product_id'].notna() &
    ~events['product_id'].isin(products['product_id'])
]

print("\n4. events.product_id → products.product_id")
print("Invalid rows:", len(invalid_events_product))


# 5. order_items.order_id → orders.order_id
invalid_items_order = order_items[
    ~order_items['order_id'].isin(orders['order_id'])
]

print("\n5. order_items.order_id → orders.order_id")
print("Invalid rows:", len(invalid_items_order))


# 6. order_items.product_id → products.product_id
invalid_items_product = order_items[
    ~order_items['product_id'].isin(products['product_id'])
]

print("\n6. order_items.product_id → products.product_id")
print("Invalid rows:", len(invalid_items_product))


# 7. reviews.order_id → orders.order_id
invalid_reviews_order = reviews[
    ~reviews['order_id'].isin(orders['order_id'])
]

print("\n7. reviews.order_id → orders.order_id")
print("Invalid rows:", len(invalid_reviews_order))


# 8. reviews.product_id → products.product_id
invalid_reviews_product = reviews[
    ~reviews['product_id'].isin(products['product_id'])
]

print("\n8. reviews.product_id → products.product_id")
print("Invalid rows:", len(invalid_reviews_product))

FOREIGN KEY INTEGRITY

1. sessions.customer_id → customers.customer_id
Invalid rows: 0

2. orders.customer_id → customers.customer_id
Invalid rows: 0

3. events.session_id → sessions.session_id
Invalid rows: 0

4. events.product_id → products.product_id
Invalid rows: 0

5. order_items.order_id → orders.order_id
Invalid rows: 0

6. order_items.product_id → products.product_id
Invalid rows: 0

7. reviews.order_id → orders.order_id
Invalid rows: 0

8. reviews.product_id → products.product_id
Invalid rows: 0

In [ ]:
print("FINAL DATA QUALITY STATUS")

for name, df in tables.items():

    print(f"\n{name.upper()}")
    print("Rows:", len(df))
    print("Columns:", len(df.columns))
    print("Duplicate rows:", df.duplicated().sum())
    print("Missing values:", df.isnull().sum().sum())

print("FINAL CHECK COMPLETED")

FINAL DATA QUALITY STATUS

CUSTOMERS
Rows: 20000
Columns: 7
Duplicate rows: 0
Missing values: 0

PRODUCTS
Rows: 1197
Columns: 6
Duplicate rows: 0
Missing values: 0

SESSIONS
Rows: 120000
Columns: 6
Duplicate rows: 0
Missing values: 0

EVENTS
Rows: 760958
Columns: 10
Duplicate rows: 0
Missing values: 3594504

ORDERS
Rows: 33580
Columns: 10
Duplicate rows: 0
Missing values: 0

ORDER_ITEMS
Rows: 59090
Columns: 5
Duplicate rows: 0
Missing values: 0

REVIEWS
Rows: 10780
Columns: 6
Duplicate rows: 0
Missing values: 0
FINAL CHECK COMPLETED

In [ ]:
cleaned_folder = '/content/drive/MyDrive/Ecommerce Business and Customer Analytics/Data/Cleaned Data'

os.makedirs(cleaned_folder, exist_ok=True)

print("Cleaned data folder created:")
print(cleaned_folder)

Cleaned data folder created:
/content/drive/MyDrive/Ecommerce Business and Customer Analytics/Data/Cleaned Data

In [ ]:
# Save cleaned DataFrames as Excel files

customers.to_excel(
    f'{cleaned_folder}/customers.xlsx',
    index=False
)

products.to_excel(
    f'{cleaned_folder}/products.xlsx',
    index=False
)

sessions.to_excel(
    f'{cleaned_folder}/sessions.xlsx',
    index=False
)

events.to_excel(
    f'{cleaned_folder}/events.xlsx',
    index=False
)

orders.to_excel(
    f'{cleaned_folder}/orders.xlsx',
    index=False
)

order_items.to_excel(
    f'{cleaned_folder}/order_items.xlsx',
    index=False
)

reviews.to_excel(
    f'{cleaned_folder}/reviews.xlsx',
    index=False
)

print("All cleaned files saved successfully!")

All cleaned files saved successfully!

In [ ]:
os.listdir(cleaned_folder)

['customers.xlsx',
 'products.xlsx',
 'sessions.xlsx',
 'events.xlsx',
 'orders.xlsx',
 'order_items.xlsx',
 'reviews.xlsx']